sudo: required
services:
  - docker

before_install:
  - docker build -t clarags/reactodocker -f Dockerfile.dev .
script: 
  - docker run -e CI=true clarags/reactodocker npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "reactodocker"
  env: "Reactodocker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-452355874645"
  bucket_path: "reactodocker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"