version: '3'
services:
  web:
    env_file: .env
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - /app/node_modules
      - .:/app
  tests:
    env_file: .env
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules
      - .:/app
    command: ["node", "/app/node_modules/react-scripts/scripts/test.js"]

